# OSPF Configurations
ospf_config:
  - process_id: 1
    network:
      - address: 192.168.0.0
        wildcard_bits: 0.0.0.255
        area: 0
      - address: 192.168.5.0
        wildcard_bits: 0.0.0.255
        area: 0

  - process_id: 2
    network:
      - address: 10.5.0.0
        wildcard_bits: 0.0.0.255
        area: 0

ospf_interface_config:
  - name: GigabitEthernet1
    address_family:
      - afi: ipv4
        process:
          id: 1
          area_id: 0